import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";

test("local User completes an unmocked journey through Next, Nest and PostgreSQL", async ({ page }) => {
  const email = `${randomUUID()}@example.com`;
  await page.goto("/login");
  await page.getByLabel("อีเมลหรือเบอร์โทร").fill(email);
  await page.getByRole("button", { name: "ดำเนินการต่อ" }).click();
  await expect(page).toHaveURL(/\/start$/);
  await page.getByLabel("เงินคงเหลือ ณ วันเริ่ม", { exact: true }).fill("1000.01");
  await page.getByLabel(/^รายรับตั้งแต่ /).fill("200.02");
  await page.getByRole("button", { name: "เริ่มเดือนแรก" }).click();
  await expect(page).toHaveURL(/\/month$/);
  await expect(page.getByRole("heading", { name: "เดือนนี้", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "เดือนนี้", exact: true })).toBeVisible();
  await page.goto("/profile");
  await expect(page.getByLabel("อีเมล")).toHaveValue(email);
  const replacement = `${randomUUID()}@example.com`;
  await page.getByLabel("อีเมล").fill(replacement);
  await page.getByLabel("วันเกิด", { exact: true }).click();
  await page.getByRole("combobox", { name: "ปี", exact: true }).selectOption("1990");
  await page.getByRole("combobox", { name: "เดือน", exact: true }).selectOption("0");
  await page.locator('[data-day="1990-01-02"]').click();
  await page.getByRole("button", { name: "บันทึกข้อมูล" }).click();
  await expect(page.getByRole("status").filter({ hasText: "บันทึกข้อมูลแล้ว" })).toContainText("บันทึกข้อมูลแล้ว");
  await page.reload();
  await expect(page.getByLabel("อีเมล")).toHaveValue(replacement);
  await expect(page.getByLabel("วันเกิด", { exact: true })).toContainText("2 ม.ค. 2533");
});
