#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

umask 077
TOTAL_STAGES=6

banner "Deledger Private Beta setup"

stage "Data safety: backup disabled"
warn "This beta has no backup or recovery path. Host, disk, volume, or operator failure can permanently lose all Deledger data."
say "No backup directory will be created and no backup or restore timer should be enabled."
write_env BACKUP_MODE "disabled"
pause "Press Enter to accept this temporary private-beta policy."

stage "Runtime: private values"
say "Values are written with mode 600 to ENV_FILE (default: .env)."
write_env APP_ORIGIN "http://deledger.internal"
write_env BUSINESS_TIME_ZONE "Asia/Bangkok"
ask_secret DATABASE_URL "PostgreSQL runtime URL (web role):"
ask CLOUDFLARE_TEAM_DOMAIN "Cloudflare team domain (https://<team>.cloudflareaccess.com):"
ask CLOUDFLARE_ACCESS_AUD "Access application audience:"
ask_secret CLOUDFLARE_TUNNEL_TOKEN "Named Tunnel connector token:"
write_env DATABASE_URL "$DATABASE_URL"
write_env CLOUDFLARE_TEAM_DOMAIN "$CLOUDFLARE_TEAM_DOMAIN"
write_env CLOUDFLARE_ACCESS_AUD "$CLOUDFLARE_ACCESS_AUD"
write_env CLOUDFLARE_TUNNEL_TOKEN "$CLOUDFLARE_TUNNEL_TOKEN"
chmod 600 "$ENV_FILE"

stage "Cloudflare: Tunnel and Access policy"
say "Create the private edge before starting the application."
open_url "https://one.dash.cloudflare.com/"
step "Create or select a named Tunnel and add a private hostname route: deledger.internal → http://web:80."
step "Create a self-hosted private Access application for deledger.internal on port 80."
step "Enable Email OTP and Authenticate with Cloudflare One Client."
step "Allow each invited email exactly; do not allow a wildcard domain. Add Gateway allow, then a lower-priority catch-all block."
step "Enroll each beta device in WARP Traffic and DNS mode."
pause "After saving the policy and enrolling the first device, press Enter."

stage "Docker: file-backed secrets and stack"
say "Compose reads database role passwords from files outside the repository and mounts each one at /run/secrets only for the services that need it."
ask DELEDGER_SECRET_DIR "Directory for Compose secret files (default /etc/deledger/secrets):"
DELEDGER_SECRET_DIR="${DELEDGER_SECRET_DIR:-/etc/deledger/secrets}"
write_env DELEDGER_SECRET_DIR "$DELEDGER_SECRET_DIR"
step "Create postgres_password, web_password, maintenance_password, and operator_password in $DELEDGER_SECRET_DIR with owner/group-readable-only permissions (for example mode 0640)."
step "Keep the migration/operator environment outside the repository."
step "Run: docker compose --env-file \"$ENV_FILE\" -f infra/compose.yaml config --quiet"
step "Run: docker compose --env-file \"$ENV_FILE\" -f infra/compose.yaml up -d --build"
pause "After PostgreSQL and web report healthy, press Enter."

stage "Database: migrate and catch up"
say "Use the migration owner connection only from the operator shell."
step "Run pnpm db:migrate with the migration DATABASE_URL from your protected operator environment."
step "Install and enable only deledger-startup-catch-up.timer from infra/systemd. Do not enable the backup or restore-verification timers."
step "Run the startup catch-up once, then verify the pg_cron job exists."
pause "After migration and catch-up complete, press Enter."

stage "Invite: exact email and WARP smoke test"
say "The application mapping and Cloudflare allow rule must use the same exact email."
ask INVITED_EMAIL "Exact invited email:"
step "Run: pnpm operator:user invite --email $INVITED_EMAIL"
step "Add the same address to the Cloudflare Access allow policy, then sign in through Email OTP on an enrolled WARP device."
step "Confirm a non-invited address is denied by Access and an archived mapped user is denied by the application."
pause "After the invited-user smoke test and denial checks complete, press Enter."

stage "Readiness: final hand-off"
say "The release check is intentionally strict and must be run with production values loaded."
step "Load the runtime env into the operator shell, then run: COMPOSE_ENV_FILE=\"$ENV_FILE\" bash scripts/verify-release.sh"
step "Open http://deledger.internal only while WARP is connected; verify /api/health/live and the authenticated application flow."
step "Record the PR, Cloudflare custody details, and the accepted no-backup risk without recording financial values."
pause "Press Enter after the final readiness check."

finish
